import Head from "next/head";
import React from "react";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { auth, db } from "../utils/firebase";
import { collection, query } from "firebase/firestore";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what others are saying!</h2>
        <Message />
      </div>
    </div>
  );
}
